### ISSUE TITLE
How do I install and run this from ESP32 running micropython?

### ISSUE THREAD

**Issue by PicoPi** [robert-hh/Micropython-Editor#1]
I have no idea how I can install this on the ESP32 dev module that has micropython installed!
How do I get this running? Read.me doesn't say anything!

**Comment by robert-hh** [comment]
pye.py is just a python module. Once you have copied it to the ESP32, either into the file system or by putting it into the flash as frozen bytecode, you run:
from pye import pye
pye("file1", "file2"; ....)
I have that "import py" line in my main.py, and pye.py in frozen bytecode. You can also use the precompiled version, which is called wipye.mpy. 
There is more documentation in the .doc/.pdf file, and I updated README.md too just now.

**Comment by PicoPi** [comment]
Thanks for the quick reply.
I am a total noob and don't understand a thing you wrote. I will go away now and learn a bit more. Right now, I am using putty on windows to talk to REPL on the ESP32 in an interactive way.
I am pretty sure your program will be useful to me, once I know what the hell I'm talking about. 
Cheers.

**Comment by Hermann-SW** [comment]
As robert-hh stated, there are multiple options to copy over the file.
I consider this method the "standard" method, because WebREPL is available on all MicroPythons:

- connect to your Micropython (eg. with "screen /dev/ttyUSB0 115200")
- configure the module either as access point (described when ypu do "help()") or as station connecting to eg; your home router
- do "import webrepl_setup" and enable webrepl

Now assuming module IP is 192.168.4.1:

- do "git clone https://github.com/micropython/webrepl.git"
- do "webrepl/webrepl_cli.py pye.py 192.168.4.1:"
- connect to module either via "screen" or "https://micropython.org/webrepl/" in browser
- do "from pye import pye"
- do res = pye('boot.py')

Be careful not to overwrite that file with unwanted changes ...

**Comment by robert-hh** [comment]
Here a few hints using pye.
- Save is actually a "save as". In the save dialog, you can always change the file name to be saved. And save first saves to a temporary file, and then renames into the final name.
- Inside pye, a new file can be opened with Ctrl-O, and Ctrl-W to change between files. If you open a directory, like '.', then the file list will be loaded. Opening a file form that list can be done by a) going with the cursor to that line, b) push Ctrl-O for open a file, and c) push Ctrl-V to paste the file name under the cursor. 
- You can use pye_mp.mpy instead of pye.py, which omits the linux code and is pre-compiled, loading faster.
