### ISSUE TITLE
how do you invoke the editor from micropython?

### ISSUE THREAD

**Issue by aguaviva** [robert-hh/Micropython-Editor#11]
It might be obvious but I can't figure it out

Thanks for this tool!

**Comment by robert-hh** [comment]
There are several variants of the file in the repository, all based on pye.py. On a micropython board I usually use the pye_mp.py. But you can also use the pye.py with the pye_gen.py front-end. I call that e.g. with:

from pye_mp import pye
pye(filename, filename...)

or 

pye()

The latter gives you an edit window with the list of files in the current directory. Ctrl-O opens a new file window. When the editor asks you for a file name, you can copy the name under the cursor with Ctrl-V. For a list of keyboard commands see the documentation. Not all Terminal emulators and shell versions support all special keys. OS X terminal for instance does not support mouse or Shift-cursor variants. Same for Putty on Windows. But the cursor keys work.

Instead of a filename you can also supply any iterable as argument, which will then be expanded into a list. May it be helpful or not.

**Comment by aguaviva** [comment]
What a great explanation, thank you!
