### ISSUE TITLE
xterm.js recently removed the Shift-Backspace behavior.  FYI

### ISSUE THREAD

**Issue by DG12** [robert-hh/Micropython-Editor#24]
Are you familiar with
https://github.com/GoogleChromeLabs/serial-terminal/issues/41

**Comment by robert-hh** [comment]
I had worked with serial terminal emulators in chrome. In that specific case discussed in the link, pye should work  as expected, since the `backspace` function is mapped to \x7f, which is what the normal PC keyboard driver provides,  ^H is mapped to `replace`. If a user cannot work with that, she or he can change the keystroke mapping table.
Besides that, serial terminal emulators behave different. If the chrome serial terminal gets a commodity, we could mention it in the documentation.
