### ISSUE TITLE
convert CR->CRLF ?

### ISSUE THREAD

**Issue by schroepfer** [robert-hh/Micropython-Editor#3]
Hello,
when i edit my code in REPL btw. pye('code.py') i only see the whole code in one line.
Is here the problem, that there are missing linefeeds?
Can i convert this in pye?

Regards
Juergen

**Comment by robert-hh** [comment]
This is most likely a Mac file, where line endings are CR. So you either have to convert that externally, or you could try the option of py to deal with lists instead of file names.

pye(open('code.py').read().split('\r'))

if you the save the content to a file, it will have linefeeds instead of CR.

**Comment by schroepfer** [comment]
Thank you! This helped!
