### ISSUE TITLE
Pathway to Minimization

### ISSUE THREAD

**Issue by joewez** [robert-hh/Micropython-Editor#8]
Hi Robert,

I absolutely love your editor and think it should be a core app for MicroPython.

I am planning on possibly forking **pye.py** for the ESP8266 to do try and carefully pare down the feature set such that the app becomes more amenable to normal use, without needing to be frozen.  I plan to keep to basic, bare set of editing features, and trash the rest.

Anyway before I get started digesting the app, do you KNOW how of any areas in the code where this could be done.

Keep up the good work!

**Comment by robert-hh** [comment]
Thank you very much. Indeed I kept for a while a version called pye_sml.py, which is somewhat smaller. The compiled version is only about half the size of the full one (8.3k vs 15.6k). Maybe that is a starting point. It has the old line based copy/cut/paste method and not redo. And it still could be slimmed down.
There is not a single property which make the editor large. Just many. So you have to consider for each function, whether it can be omitted. Some of these:
- Jump to a matching bracket.
- skip word left/right
- delete word
- mouse support, including scrlup and scrdn.
- Regular expressions in search. There is a file called tuning_pye, which has a simple search.
- A simple version of line edit (also in tuning_pye.py)
- Replace
- You can drop the functions for scroll-up/down. Scrolling will then be done by screen repaint.
- Block Indent/dedent.

Cut/copy/paste is a big block. But I would keep it.
Undo/redo is also a big part of it, but useful and hard to remove.

But you will most likely not be able to get it down to ESP8266 size, even with precompiling.
Without precompiling, ~350 LOC is the limit for ESP8266.  Since the full version runs well on an esp8266 as frozen bytecode, I stopped any optimization and kept the RAM for the edit buffer.

There are the I/O sections for Linux and MP. In the moment I'm in the process of modularizing it into a editor core file and a front-end with the I/O section. That does not make it much smaller, but better structured.

**Comment by robert-hh** [comment]
More convenience functions that could be omitted:
- shifting lines/blocks up/down (Alt-Up/down)
- Block comment toggle

**Comment by joewez** [comment]
Thank you Robert!
That is a lot of valuable information that I will we be digesting in the next day or two as I go over the code.  To clarify, I intended the editor to be functional enough to make quick edits, but not much else. 

It's too bad that the ESP8266 has such limitations... but I am optimistic.  I think it's my mission in life to see how much I can squeeze out of these little things!

Again, thank you for your time and lending me your knowledge...

Joe

**Comment by robert-hh** [comment]
I just mad a quick test: the precompiled version of pye_sml.py works on an ESP8266.

**Comment by joewez** [comment]
That's awesome... I think I will begin there!

**Comment by robert-hh** [comment]
I made a branch called pye_min, which contains a version halfway between the actual full feature pye.py and the pye_sml.py version. The compiled sizes are:
pye_mp.mpy:  full version 15.5k
pye_mp.mpy:  smaller version 12.2k
pye_sml.mpy: 8.3k
I have removed the stuff listed above, but kept undo/redo and cut/copy/paste in the character granularity. Scrolling and block indent/dedent is also still there.

**Comment by joewez** [comment]
Robert, fantastic work!
I have been testing out the "smaller" version and it works great.  I think I can achieve my goals with this new version.

I am particularly keen on trying to make MicroPython on the ESP8266 a serious platform for micro controller development with a very low barrier to entry.  Perhaps for educational purposes.  I can get a D1 Mini clone for $2 these days and with a USB cable and with your onboard editor, I can do some pretty cool things.

I appreciate your efforts. Thank you.
