### ISSUE TITLE
Micropython-editor was mentioned. 

### ISSUE THREAD

**Issue by kmatch98** [robert-hh/Micropython-Editor#9]
The Micropython-editor was featured in this CircuitPython newsletter this week!  Look about halfway down.
https://www.adafruitdaily.com/2020/05/19/fifty-blinka-boards-python-survey-out-cp-5-4-0-beta-0-and-more-python-adafruit-circuitpython-circuitpython-micropython-thepsf/

**Comment by robert-hh** [comment]
Yes. Thanks for the note. I used installed Circuitpython on one of the otherwise unused boards I had in my drawer, a Teensy 4.0. What puzzles me is, that the code runs comparably slow, given that the Teensy4 runs at 600MHz, compared to a STM32 with Micropython running at 168 MHz, or an ESP8266 at 80 MHz.
I see the attempts of Adafruit to make it look the same on all boards, and make the File access by a USB drive robust, but there seem no officially supported board with WiFi. That's strange. There is a port for the upcoming esp32s2, but these modules are not in widespread sales yet.

**Comment by robert-hh** [comment]
By the way: I renamed the branches in the repository. master -> master_old, modules -> master.
That might cause trouble in pulling.

**Comment by kmatch98** [comment]
It’s strange what you say about the performance.  I’ve heard some chatter about the lates beta version for CircuitPython is having performance issues while they are updating some low power handling capabilities with some excess background processing.  

But if you were running on the released version of the CIrcuitPython code I wouldn’t suspect any issues. Perhaps this is worthy of an issue, especially since I hear the Teensy 4.0-like chip is gaining a lot more interest. 

And thanks for the heads up on the name changes. 

As for no WiFi chips for CircuitPython, the best you can do right now is add a WiFi coprocessor, until the ESP32-S2 arrives.
